# Generated by Django 3.0.4 on 2020-04-01 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=50)),
                ('Answer', models.TextField()),
                ('Votes', models.SmallIntegerField(default=0)),
                ('added_date', models.DateTimeField()),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='forum.Question')),
            ],
        ),
    ]
