# Generated by Django 3.0.4 on 2020-04-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='Author',
            field=models.TextField(verbose_name='auth.User'),
        ),
    ]
